import { Container, Footer, Header } from '@/components/shared';
import { Metadata } from 'next';
import { Suspense } from 'react';

export const metadata: Metadata = {
  title: 'Next Parts | Оплата заказа',
  description: 'Generated by Next.js',
};

export default function TestPayLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Suspense>
        <Header hasSearch={false} hasCart={false} className="border-b-gray-200" />
      </Suspense>
      <div className="min-h-[calc(100vh-100px-100px)] bg-[#f4f1ee]">
        <Container>{children}</Container>
      </div>
      <Footer />
    </>
  );
}
