import { Container, Footer, Header } from '@/components/shared';
import { getUserSession } from '@/lib/get-user-session';
import { redirect } from 'next/navigation';
import { Suspense } from 'react';

export const metadata = {
  title: 'Панель администратора',
  description: 'Generated by Next.js',
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // проверка авторизации на уровне сервера
  const session = await getUserSession();

  if (!session || (session?.role !== 'ADMIN' && session?.role !== 'MANAGER')) {
    return redirect('/not-auth');
  }

  return (
    <>
      <Suspense>
        <Header hasSearch={false} hasCart={false} className="border-b-gray-200" />
      </Suspense>
      <div className="min-h-[calc(100vh-100px-100px)] bg-[#f4f1ee] pb-5">
        <Container>{children}</Container>
      </div>
      <Footer />
    </>
  );
}
