import { Container, Header } from '@/components/shared';
import { getUserSession } from '@/lib/get-user-session';
import { redirect } from 'next/navigation';

export const metadata = {
  title: 'Панель администратора',
  description: 'Generated by Next.js',
};

export default async function DashboardLayout({ children }: { children: React.ReactNode }) {
  // проверка авторизации на уровне сервера
  const session = await getUserSession();

  if (!session || session?.role !== 'ADMIN') {
    return redirect('/not-auth');
  }

  return (
    <main className="min-h-screen bg-[#f4f1ee]">
      <Container>
        <Header hasSearch={false} hasCart={false} className="border-b-gray-200" />
        {children}
      </Container>
    </main>
  );
}
